{{- if .Values.dynamodbSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sandbox-assignment-api.fullname" . }}-dynamodb
type: Opaque
data:
  aws_region: {{ .Values.dynamodbSecret.aws_region | b64enc }}
  aws_access_key_id: {{ .Values.dynamodbSecret.aws_access_key_id | b64enc }}
  aws_secret_access_key: {{ .Values.dynamodbSecret.aws_secret_access_key | b64enc }}
{{- end -}}
