{{- if .Values.jwtSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sandbox-assignment-api.fullname" . }}-jwt
type: Opaque
data:
  jwt_secret_key: {{ .Values.jwtSecret.key | default (randAlphaNum 64) | b64enc }}
{{- end -}}
